In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [32]:
df = pd.read_csv('C:\\Users\\satap\\OneDrive\\Desktop\\STEVENS\\CS-513\\breast-cancer-wisconsin.csv')

In [33]:
header_names = ["SampleCode", "ClumpThickness", "UniformityCellSize", "UniformityCellShape", "MarginalAdhesion", "SingleEpithelialCellSize", "BareNuclei", "BlandChromatin", "NormalNucleoli", "Mitoses", "Class"]

In [34]:
df =  pd.read_csv('C:\\Users\\satap\\OneDrive\\Desktop\\STEVENS\\CS-513\\breast-cancer-wisconsin.csv',header=None,skiprows=1, names=header_names,na_values='?')
df

SampleCode  ClumpThickness  UniformityCellSize  UniformityCellShape  \
0       1000025               5                   1                    1   
1       1002945               5                   4                    4   
2       1015425               3                   1                    1   
3       1016277               6                   8                    8   
4       1017023               4                   1                    1   
..          ...             ...                 ...                  ...   
694      776715               3                   1                    1   
695      841769               2                   1                    1   
696      888820               5                  10                   10   
697      897471               4                   8                    6   
698      897471               4                   8                    8   

     MarginalAdhesion  SingleEpithelialCellSize  BareNuclei  BlandChromatin  \
0                   1                         2         1.0               3   
1                   5                         7        10.0               3   
2                   1                         2         2.0               3   
3                   1                         3         4.0               3   
4                   3                         2         1.0               3   
..                ...                       ...         ...             ...   
694                 1                         3         2.0               1   
695                 1                         2         1.0               1   
696                 3                         7         3.0               8   
697                 4                         3         4.0              10   
698                 5                         4         5.0              10   

     NormalNucleoli  Mitoses  Class  
0                 1        1      2  
1                 2        1      2  
2                 1        1      2  
3                 7        1      2  
4                 1        1      2  
..              ...      ...    ...  
694               1        1      2  
695               1        1      2  
696              10        2      4  
697               6        1      4  
698               4        1      4  

[699 rows x 11 columns]

In [35]:
df.dropna(axis=0,inplace=True)

In [36]:
df

SampleCode  ClumpThickness  UniformityCellSize  UniformityCellShape  \
0       1000025               5                   1                    1   
1       1002945               5                   4                    4   
2       1015425               3                   1                    1   
3       1016277               6                   8                    8   
4       1017023               4                   1                    1   
..          ...             ...                 ...                  ...   
694      776715               3                   1                    1   
695      841769               2                   1                    1   
696      888820               5                  10                   10   
697      897471               4                   8                    6   
698      897471               4                   8                    8   

     MarginalAdhesion  SingleEpithelialCellSize  BareNuclei  BlandChromatin  \
0                   1                         2         1.0               3   
1                   5                         7        10.0               3   
2                   1                         2         2.0               3   
3                   1                         3         4.0               3   
4                   3                         2         1.0               3   
..                ...                       ...         ...             ...   
694                 1                         3         2.0               1   
695                 1                         2         1.0               1   
696                 3                         7         3.0               8   
697                 4                         3         4.0              10   
698                 5                         4         5.0              10   

     NormalNucleoli  Mitoses  Class  
0                 1        1      2  
1                 2        1      2  
2                 1        1      2  
3                 7        1      2  
4                 1        1      2  
..              ...      ...    ...  
694               1        1      2  
695               1        1      2  
696              10        2      4  
697               6        1      4  
698               4        1      4  

[683 rows x 11 columns]

In [37]:
df['Class'] = df['Class'].map({2: 'Benign', 4: 'Malignant'}).fillna(df['Class'])

In [38]:
df

SampleCode  ClumpThickness  UniformityCellSize  UniformityCellShape  \
0       1000025               5                   1                    1   
1       1002945               5                   4                    4   
2       1015425               3                   1                    1   
3       1016277               6                   8                    8   
4       1017023               4                   1                    1   
..          ...             ...                 ...                  ...   
694      776715               3                   1                    1   
695      841769               2                   1                    1   
696      888820               5                  10                   10   
697      897471               4                   8                    6   
698      897471               4                   8                    8   

     MarginalAdhesion  SingleEpithelialCellSize  BareNuclei  BlandChromatin  \
0                   1                         2         1.0               3   
1                   5                         7        10.0               3   
2                   1                         2         2.0               3   
3                   1                         3         4.0               3   
4                   3                         2         1.0               3   
..                ...                       ...         ...             ...   
694                 1                         3         2.0               1   
695                 1                         2         1.0               1   
696                 3                         7         3.0               8   
697                 4                         3         4.0              10   
698                 5                         4         5.0              10   

     NormalNucleoli  Mitoses      Class  
0                 1        1     Benign  
1                 2        1     Benign  
2                 1        1     Benign  
3                 7        1     Benign  
4                 1        1     Benign  
..              ...      ...        ...  
694               1        1     Benign  
695               1        1     Benign  
696              10        2  Malignant  
697               6        1  Malignant  
698               4        1  Malignant  

[683 rows x 11 columns]

In [39]:
X = df.drop(columns=['SampleCode', 'Class'])
y = df['Class']

In [40]:
X = pd.DataFrame(MinMaxScaler().fit_transform(X), columns=X.columns)

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [42]:
knn_3 = KNeighborsClassifier(n_neighbors=3)
knn_5 = KNeighborsClassifier(n_neighbors=5)
knn_10 = KNeighborsClassifier(n_neighbors=10)

In [43]:
knn_3.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [44]:
knn_5.fit(X_train,y_train)

KNeighborsClassifier()

In [45]:
knn_10.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [46]:
y_pred_3 = knn_3.predict(X_test)
y_pred_5 = knn_5.predict(X_test)
y_pred_10 = knn_10.predict(X_test)

In [47]:
conf_matrix_3 = confusion_matrix(y_test, y_pred_3)
print(conf_matrix_3)

[[114   2]
 [  6  83]]


In [48]:
conf_matrix_5 = confusion_matrix(y_test, y_pred_5)
print(conf_matrix_5)

[[114   2]
 [  2  87]]


In [49]:
conf_matrix_10 = confusion_matrix(y_test, y_pred_10)
print(conf_matrix_10)

[[114   2]
 [  3  86]]


In [50]:
accuracy_3 = accuracy_score(y_test, y_pred_3) * 100
print(f'Accuracy: {accuracy_3:.2f}%')

Accuracy: 96.10%


In [51]:
accuracy_5 = accuracy_score(y_test, y_pred_5) * 100
print(f'Accuracy: {accuracy_5:.2f}%')

Accuracy: 98.05%


In [52]:
accuracy_10 = accuracy_score(y_test, y_pred_10) * 100
print(f'Accuracy: {accuracy_10:.2f}%')

Accuracy: 97.56%
